FROM {{ parent }}
ARG PYTHON_VERSION={{ PYTHON_VERSION }}

RUN apt update && apt install -y \
    build-essential \
    libssl-dev \
    pkg-config \
    wget \
    tar \
    make

WORKDIR /tmp

# https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz
# https://www.python.org/ftp/python/3.8.19/Python-3.8.19.tar.xz
RUN wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz \
    && tar -xf Python-${PYTHON_VERSION}.tar.xz \
    && cd Python-${PYTHON_VERSION} \
    && ./configure --enable-optimizations --with-openssl=/usr/include/openssl \
    && make \
    && make install

WORKDIR /