FROM {{ parent }}
ARG PYTHON_VERSION={{ PYTHON_VERSION }}

RUN apt update && apt install -y \
    build-essential \
    libssl-dev \
    libffi-dev \
    libbz2-dev \
    zlib1g-dev \
    libncurses5-dev \
    libsqlite3-dev \
    libreadline-dev \
    libgdm-dev \
    pkg-config \
    wget \
    tar \
    make

WORKDIR /tmp

# Python fetched from https://www.python.org/ftp/python/
RUN wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tar.xz \
    && tar -xf Python-${PYTHON_VERSION}.tar.xz \
    && cd Python-${PYTHON_VERSION} \
    && ./configure --enable-optimizations \
    && make \
    && make install

WORKDIR /