environments:
  docker_image_main:
    environment_variables:
      DOCKERHUB_PASSWORD: '{{SECRET:[dockerhub][password]}}'
      DOCKERHUB_USERNAME: '{{SECRET:[dockerhub][username]}}'
    pipelines:
    - docker-gocd-agent-python-3.8
    - docker-gocd-agent-python-3.9
    - docker-gocd-agent-python-3.10
    - docker-gocd-agent-python-3.11
    - docker-gocd-agent-python-3.12
    - docker-gocd-agent-python-latest
    - docker-gocd-agent-python-edge
format_version: 10
pipelines:
  docker-gocd-agent-python-3.10:
    display_order: -1
    group: docker_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: main
        destination: docker-gocd-agent-python
        git: https://github.com/ucphhpc/docker-gocd-agent-python.git
      upstream_docker-gocd-agent-python:
        pipeline: gocd-agent-docker-v23.4.0
        stage: push
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_DOCKER_GOCD_AGENT_PYTHON
      DEFAULT_TAG: '3.10'
      EXTRA_TAG: ''
      IMAGE: docker-gocd-agent-python
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: docker-gocd-agent-python
      TEST_DIRECTORY: docker-gocd-agent-python
    template: docker_image
    timer: &id001
      only_on_changes: 'no'
      spec: 0 0 0 1 * ?
  docker-gocd-agent-python-3.11:
    display_order: -1
    group: docker_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: main
        destination: docker-gocd-agent-python
        git: https://github.com/ucphhpc/docker-gocd-agent-python.git
      upstream_docker-gocd-agent-python:
        pipeline: gocd-agent-docker-v23.4.0
        stage: push
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_DOCKER_GOCD_AGENT_PYTHON
      DEFAULT_TAG: '3.11'
      EXTRA_TAG: ''
      IMAGE: docker-gocd-agent-python
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: docker-gocd-agent-python
      TEST_DIRECTORY: docker-gocd-agent-python
    template: docker_image
    timer: *id001
  docker-gocd-agent-python-3.12:
    display_order: -1
    group: docker_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: main
        destination: docker-gocd-agent-python
        git: https://github.com/ucphhpc/docker-gocd-agent-python.git
      upstream_docker-gocd-agent-python:
        pipeline: gocd-agent-docker-v23.4.0
        stage: push
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_DOCKER_GOCD_AGENT_PYTHON
      DEFAULT_TAG: '3.12'
      EXTRA_TAG: ''
      IMAGE: docker-gocd-agent-python
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: docker-gocd-agent-python
      TEST_DIRECTORY: docker-gocd-agent-python
    template: docker_image
    timer: *id001
  docker-gocd-agent-python-3.8:
    display_order: -1
    group: docker_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: main
        destination: docker-gocd-agent-python
        git: https://github.com/ucphhpc/docker-gocd-agent-python.git
      upstream_docker-gocd-agent-python:
        pipeline: gocd-agent-docker-v23.4.0
        stage: push
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_DOCKER_GOCD_AGENT_PYTHON
      DEFAULT_TAG: '3.8'
      EXTRA_TAG: ''
      IMAGE: docker-gocd-agent-python
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: docker-gocd-agent-python
      TEST_DIRECTORY: docker-gocd-agent-python
    template: docker_image
    timer: *id001
  docker-gocd-agent-python-3.9:
    display_order: -1
    group: docker_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: main
        destination: docker-gocd-agent-python
        git: https://github.com/ucphhpc/docker-gocd-agent-python.git
      upstream_docker-gocd-agent-python:
        pipeline: gocd-agent-docker-v23.4.0
        stage: push
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_DOCKER_GOCD_AGENT_PYTHON
      DEFAULT_TAG: '3.9'
      EXTRA_TAG: ''
      IMAGE: docker-gocd-agent-python
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: docker-gocd-agent-python
      TEST_DIRECTORY: docker-gocd-agent-python
    template: docker_image
    timer: *id001
  docker-gocd-agent-python-edge:
    display_order: -1
    group: docker_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: main
        destination: docker-gocd-agent-python
        git: https://github.com/ucphhpc/docker-gocd-agent-python.git
      upstream_docker-gocd-agent-python:
        pipeline: gocd-agent-docker-v23.4.0
        stage: push
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_DOCKER_GOCD_AGENT_PYTHON
      DEFAULT_TAG: edge
      EXTRA_TAG: ''
      IMAGE: docker-gocd-agent-python
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: docker-gocd-agent-python
      TEST_DIRECTORY: docker-gocd-agent-python
    template: docker_image
    timer: *id001
  docker-gocd-agent-python-latest:
    display_order: -1
    group: docker_image
    label_template: ${COUNT}
    lock_behaviour: none
    materials:
      publish_docker_git:
        branch: main
        destination: publish-docker-scripts
        git: https://github.com/rasmunk/publish-docker-scripts.git
        password: '{{SECRET:[github][access_token]}}'
        username: ${GIT_USER}
      ucphhpc_images:
        branch: main
        destination: docker-gocd-agent-python
        git: https://github.com/ucphhpc/docker-gocd-agent-python.git
      upstream_docker-gocd-agent-python:
        pipeline: gocd-agent-docker-v23.4.0
        stage: push
    parameters:
      ARGS: ''
      COMMIT_TAG: GO_REVISION_DOCKER_GOCD_AGENT_PYTHON
      DEFAULT_TAG: latest
      EXTRA_TAG: ''
      IMAGE: docker-gocd-agent-python
      PUSH_DIRECTORY: publish-docker-scripts
      SRC_DIRECTORY: docker-gocd-agent-python
      TEST_DIRECTORY: docker-gocd-agent-python
    template: docker_image
    timer: *id001
